[key_info]
seed=42
year=2024
month=1

[unit]
unit_name="USF Teste"
number_of_doctors=5
number_of_nurses=5

[population]
num_individuals = 100
age_range = [0, 100]
sex_ratio = 0.5

[disease_distribution]
[K86]
prevalence = 0.2
age_range = [35, 100]

[K87]
prevalence = 0.15
age_range = [45, 100]

